default: &default
  adapter: sqlite3

development:
  <<: *default
  database: db/development.sqlite3
test:
  adapter: sqlite3
  database: ':memory:'
production:
  <<: *default
  database: db/production.sqlite3
