default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tht_gh_search_development
test:
  adapter: sqlite3
  database: ':memory:'
production:
  <<: *default
  database: tht_gh_search_production
  username: tht_gh_search
  password: <%= ENV['THT_GH_SEARCH_DATABASE_PASSWORD'] %>
