default: &default
  adapter: sqlite3

development:
  <<: *default
  database: db/development.sqlite3
test:
  adapter: sqlite3
  database: ':memory:'
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  database: tht_gh_search_production
